### ISSUE TITLE
Mention TruffleRuby in the README

### ISSUE THREAD

**Issue by eregon** [Talkdesk/warm-blanket#9]
Hello,

It looks like this project could be useful to run applications running on TruffleRuby.
Could you mention TruffleRuby in addition to JRuby in the README?
This should help people googling for warming up a service with TruffleRuby.
I'd make a PR myself but with the LGPL it's actually not so straightforward for me to do it.

**Comment by ivoanjo** [comment]
cc @rfelix I don't have access anymore to help out here ;)

**Comment by rfelix** [comment]
Thanks @eregon - the README has been amended and merged 😉
